# Generated by Django 5.2.1 on 2025-05-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodManager', '0005_remove_meal_ingredients_remove_meal_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='foodManager.meal')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetable',
                'ordering': ['day_of_week', 'time'],
            },
        ),
    ]
