# Generated by Django 5.2.1 on 2025-05-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableManager', '0002_alter_timetable_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=20),
        ),
    ]
