# Generated by Django 5.2.1 on 2025-06-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableManager', '0003_alter_timetable_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day_of_week', 'meal_type'], 'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetable'},
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='meal_type',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
