# Generated by Django 5.2.3 on 2025-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableManager', '0004_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20),
        ),
    ]
