# Generated by Django 5.2.1 on 2025-05-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbs',
            name='constituents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drinks',
            name='constituents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='constituents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greens',
            name='constituents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteins',
            name='constituents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treats',
            name='constituents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
