# Generated by Django 5.2.1 on 2025-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodManager', '0003_ingredient_meal_delete_carbs_delete_drinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='preference',
        ),
        migrations.AddField(
            model_name='meal',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('rarely', 'Rarely')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='preference',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
