# Generated by Django 5.2.1 on 2025-05-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodManager', '0004_remove_ingredient_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='preference',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
