# Generated by Django 5.2.1 on 2025-05-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodManager', '0005_remove_meal_ingredients_remove_meal_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meals', to='foodManager.ingredient'),
        ),
    ]
