# Generated by Django 5.2.1 on 2025-05-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodManager', '0006_ingredient_meal_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
    ]
